import 'package:flutter/material.dart';

const primaryColor = Color(0xFF28D8AE);
const foregroundColor = Color(0xFFF3F2F7);
const backgroundColor = Color(0xFFFAFAFA);
const primaryHoverColor = Color(0xFF30A79F);
const mutedColor = Color(0xFFC8C5C5);
const secondaryColor = Color(0xFFD19F54);
const flatColor = Color(0xFF28D8AE);
const blackColor = Color(0xFF1F292F);
const announcementColor = Color(0xFFFCBE45);
const dangerColor = Color(0xFFFA5057);
const whiteColor = Color(0xFFFFFFFF);
const midGrayColor = Color(0xFFEFEFEF);
const iconColor = Color(0xFF1C274C);
const scaffoldBackgroundColor = Color(0xFFE5E5E5);
const startingColor = Color(0xFF8C5AA6);
const strieghtLineColor = Color(0xFF939393);
const lightGreyColor = Color(0xFFF3F4F7);
const overGreyColor = Color(0xFF464646);
const extraGreyColor = Color(0xFF939393);
